# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: CPREgroup
# Description of the Site
description: Computational Photography Research & Engineering
# URL of Image of the Site
site-image: assets/images/background.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1136954568@qq.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username: chenchen772
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: chenchen772
# URL for the Image of the Author
author-image: assets/images/user.jpg
# 60 Words About the Author
author-about: 教育背景：访问学者（2013-2014） 合作导师 Prof.Aditi Majumder
美国加州大学欧文分校（UCI）

博士研究生 (2010-2016) 导师 鲁东明教授
浙江大学计算机科学与技术学院
本科 (2006-2010)
浙江大学计算机科学与技术学院

工作经历：宁波大学信息学院 副教授（2016-至今）

高级访问学者（2019-2021） 导师 IEEE Fellow Prof. Wolfgang Heidrich
沙特阿卜杜拉国王科技大学



目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/CPREgroup

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
